from elevenlabs_helper.engine.config import Deliverable
from elevenlabs_helper.engine.elevenlabs.models import TranscriptionResult
from elevenlabs_helper.engine.exporters import srt as srt_exporter
from elevenlabs_helper.engine.exporters import vtt as vtt_exporter
from elevenlabs_helper.engine.exporters.canonical import build_transcript
from elevenlabs_helper.engine.exporters.writer import write_deliverables

from .conftest import CANNED_RESULT


def _result() -> TranscriptionResult:
    return TranscriptionResult.model_validate(CANNED_RESULT)


def test_build_transcript_splits_on_speaker_and_gap():
    t = build_transcript(_result())
    assert t.multi_speaker is True
    assert len(t.cues) == 2
    assert t.cues[0].speaker_id == "speaker_0"
    assert t.cues[1].speaker_id == "speaker_1"
    assert "Hello world." in t.cues[0].text


def test_srt_marks_speaker_change_with_dash_no_labels():
    out = srt_exporter.render(build_transcript(_result()))
    assert "00:00:00,000 --> 00:00:01,000" in out
    assert "Speaker" not in out  # no "Speaker N:" labels in captions
    # First speaker establishes (no dash); the change to speaker_1 gets a dash.
    assert "Hello world." in out
    assert "- How are you?" in out


def test_vtt_marks_speaker_change_with_dash_no_voice_tags():
    out = vtt_exporter.render(build_transcript(_result()))
    assert out.startswith("WEBVTT")
    assert "NOTE Generated by ElevenLabs Scribe (AI)" in out  # provenance comment
    assert "00:00:00.000 --> 00:00:01.000" in out
    assert "<v" not in out and "Speaker" not in out
    assert "- How are you?" in out


def test_audio_event_cue_has_no_speaker_and_no_dash():
    # speaker dialogue, then a pure audio event (different speaker_id), then dialogue.
    data = {
        "text": "Hi there bye",
        "words": [
            {"text": "Hi", "start": 0.0, "end": 0.4, "type": "word", "speaker_id": "speaker_0"},
            {"text": "there", "start": 0.5, "end": 0.9, "type": "word", "speaker_id": "speaker_0"},
            {"text": "[music]", "start": 2.0, "end": 4.0, "type": "audio_event", "speaker_id": "speaker_1"},
            {"text": "bye", "start": 5.0, "end": 5.4, "type": "word", "speaker_id": "speaker_0"},
        ],
    }
    t = build_transcript(TranscriptionResult.model_validate(data))
    out = srt_exporter.render(t)
    assert "(music)" in out          # audio event rendered, wrapped in parens
    assert "- (music)" not in out    # no speaker-change dash on an audio event
    # The music's speaker_1 must NOT cause a spurious dash on the returning "bye".
    assert "- bye" not in out


def test_writer_emits_selected_plus_raw_json(tmp_path):
    artifacts = write_deliverables(
        _result(), tmp_path, "clip", [Deliverable.SRT, Deliverable.VTT, Deliverable.DOCX]
    )
    assert (tmp_path / "clip.srt").exists()
    assert (tmp_path / "clip.vtt").exists()
    assert (tmp_path / "clip.docx").exists()
    assert (tmp_path / "clip.raw.json").exists()  # always written
    assert set(artifacts) == {"srt", "vtt", "docx", "json"}
