"""Caption-document renderers preserve the interpreted text/timing contract."""

from __future__ import annotations

import pytest

from elevenlabs_helper.engine.captions import (
    HOUSE_ENGLISH_V1,
    CaptionDocument,
    CaptionEvent,
    CaptionExportOptions,
    CaptionTimingMode,
)
from elevenlabs_helper.engine.exporters import srt, vtt


def _document(*lines: str) -> CaptionDocument:
    options = CaptionExportOptions(timing_mode=CaptionTimingMode.HOUSE)
    return CaptionDocument(
        profile=HOUSE_ENGLISH_V1,
        options=options,
        source_hash="source",
        speaker_overlay_hash="overlay",
        events=(
            CaptionEvent(
                start=1.2344,
                end=3.4566,
                authored_lines=lines,
                source_token_indices=(0, 1),
                timing_mode=CaptionTimingMode.HOUSE,
            ),
        ),
        provenance={"test": True},
    )


def test_srt_uses_authored_lines_and_document_timing_verbatim() -> None:
    rendered = srt.render_caption_document(_document("First line", "Second line"))

    assert "00:00:01,234 --> 00:00:03,457" in rendered
    assert "First line\nSecond line" in rendered


def test_vtt_is_style_free_and_escapes_cue_syntax_as_display_text() -> None:
    rendered = vtt.render_caption_document(_document("Use <literal> & text"))

    assert "00:00:01.234 --> 00:00:03.457" in rendered
    assert "Use &lt;literal&gt; &amp; text" in rendered
    assert "<v" not in rendered and "STYLE" not in rendered and "REGION" not in rendered
    assert "NOTE Generated by ElevenLabs Scribe (AI)" in rendered


@pytest.mark.parametrize("renderer", [srt.render_caption_document, vtt.render_caption_document])
def test_renderers_reject_embedded_newline_in_authored_line(renderer) -> None:
    with pytest.raises(ValueError, match="embedded newlines"):
        renderer(_document("injected\n\n00:01.000 --> 00:02.000"))


def test_legacy_transcript_entry_points_remain_available() -> None:
    from elevenlabs_helper.engine.exporters.canonical import Cue, Transcript

    transcript = Transcript(cues=[Cue(1, 0.0, 1.0, "Legacy")])
    assert "Legacy" in srt.render(transcript)
    assert "Legacy" in vtt.render(transcript)
