"""Stage 2 remediation coverage (E3 cap, SSR-007 redaction, AI disclosure, E6 store guard)."""

from __future__ import annotations

from datetime import datetime, timedelta, timezone

import httpx

from elevenlabs_helper.engine.config import EngineSettings
from elevenlabs_helper.engine.elevenlabs.client import _error_text
from elevenlabs_helper.engine.elevenlabs.models import TranscriptionResult
from elevenlabs_helper.engine.exporters import docx as docx_exporter
from elevenlabs_helper.engine.exporters.canonical import build_transcript
from elevenlabs_helper.engine.jobs.models import Job
from elevenlabs_helper.engine.jobs.store import JobStore
from elevenlabs_helper.engine.service import Engine

from .conftest import CANNED_RESULT


def test_list_jobs_limit_keeps_newest_oldest_first(tmp_path):
    store = JobStore(db_path=tmp_path / "j.db")
    base = datetime(2026, 6, 1, tzinfo=timezone.utc)
    for i in range(3):
        store.upsert(Job(source_path=f"{i}.mp3", output_dir="o", created_at=base + timedelta(minutes=i)))
    newest_two = store.list_jobs(limit=2)
    assert [j.source_path for j in newest_two] == ["1.mp3", "2.mp3"]  # newest 2, oldest-first
    store.close()


def test_error_text_is_truncated(tmp_path):
    resp = httpx.Response(400, json={"detail": "x" * 5000})
    text = _error_text(resp)
    assert text.startswith("HTTP 400:")
    assert len(text) < 230  # body not dumped wholesale into the persisted error


def test_docx_carries_ai_disclosure(tmp_path):
    from docx import Document

    transcript = build_transcript(TranscriptionResult.model_validate(CANNED_RESULT))
    out = tmp_path / "t.docx"
    docx_exporter.write(transcript, out)
    text = "\n".join(p.text for p in Document(str(out)).paragraphs)
    assert "Generated by ElevenLabs Scribe (AI)" in text


def test_engine_stop_does_not_close_shared_store(tmp_path):
    store = JobStore(db_path=tmp_path / "j.db")
    engine = Engine(settings=EngineSettings(), store=store, base_url="https://api.elevenlabs.io")
    engine.stop()  # must NOT close a caller-provided store
    assert store.list_jobs() == []  # still usable
    store.close()
