"""Render a Transcript to a formatted Word document.

Consecutive cues from the same speaker are merged into one paragraph; each
paragraph is prefixed with a timecode and (when diarized) a speaker label.
"""

from __future__ import annotations

from pathlib import Path

from docx import Document

from .canonical import Transcript


def _tc(seconds: float) -> str:
    seconds = max(0, int(round(seconds)))
    h, rem = divmod(seconds, 3600)
    m, s = divmod(rem, 60)
    return f"{h:02d}:{m:02d}:{s:02d}"


def write(transcript: Transcript, out_path: str | Path) -> Path:
    out_path = Path(out_path)
    doc = Document()
    doc.add_heading("Transcript", level=0)
    # AI-generated disclosure (AIUC Global): mark redistributed deliverables.
    disclosure = doc.add_paragraph()
    disclosure.add_run(
        "Generated by ElevenLabs Scribe (AI) — verify accuracy before relying on it."
    ).italic = True
    if transcript.language_code:
        meta = doc.add_paragraph()
        meta.add_run(f"Detected language: {transcript.language_code}").italic = True

    cur_speaker: str | None = None
    para = None
    for cue in transcript.cues:
        if para is None or cue.speaker_id != cur_speaker:
            para = doc.add_paragraph()
            prefix = f"[{_tc(cue.start)}] "
            if transcript.multi_speaker and not cue.is_audio_event:
                prefix += f"{transcript.speaker_label(cue.speaker_id)}: "
            run = para.add_run(prefix)
            run.bold = True
            para.add_run(cue.text)
            cur_speaker = cue.speaker_id
        else:
            para.add_run(" " + cue.text)

    doc.save(str(out_path))
    return out_path
