"""Render a Transcript to WebVTT.

Speaker changes are marked with a leading ``- `` (no voice tags / "Speaker N:"
labels); audio-event cues are rendered bare.
"""

from __future__ import annotations

from .canonical import Transcript, caption_lines


def _ts(seconds: float) -> str:
    if seconds < 0:
        seconds = 0
    ms = int(round(seconds * 1000))
    h, ms = divmod(ms, 3_600_000)
    m, ms = divmod(ms, 60_000)
    s, ms = divmod(ms, 1000)
    return f"{h:02d}:{m:02d}:{s:02d}.{ms:03d}"


def render(transcript: Transcript) -> str:
    # WebVTT NOTE blocks are comments (ignored by players) — used here for AI provenance.
    out: list[str] = ["WEBVTT", "", "NOTE Generated by ElevenLabs Scribe (AI) — verify accuracy.", ""]
    for cue, text in zip(transcript.cues, caption_lines(transcript)):
        out.append(f"{_ts(cue.start)} --> {_ts(cue.end)}")
        out.append(text)
        out.append("")
    return "\n".join(out)
