"""Caption authoring contracts and built-in profiles.

Interpretation and rendering are added by later packets; importing this package
is deliberately free of GUI, file-system, and network side effects.
"""

from .models import (
    CAPTION_ALGORITHM_VERSION,
    CAPTION_SCHEMA_VERSION,
    CONTRACT_EXAMPLES,
    CaptionBaselineCue,
    CaptionApproval,
    CaptionCharacterRange,
    CaptionContentKind,
    CaptionContext,
    CaptionDestinationOverride,
    CaptionDocument,
    CaptionEditorialCoverage,
    CaptionEvent,
    CaptionExceptionState,
    CaptionExportOptions,
    CaptionExportPolicy,
    CaptionFrameRate,
    CaptionInterpretation,
    CaptionIssueSeverity,
    CaptionQCIssue,
    CaptionQCReport,
    CaptionProfile,
    CaptionRenderingDisposition,
    CaptionSource,
    CaptionSourceToken,
    CaptionTechnicalStatus,
    CaptionTimingMode,
    ExportResult,
    InvalidNumericValue,
    canonical_json,
    deterministic_hash,
    deterministic_id,
)
from .profiles import HOUSE_ENGLISH_V1, available_caption_profiles, get_caption_profile
from .glyphs import UnsupportedGlyph, is_supported_glyph, repertoire_metadata, unsupported_glyphs
from .interpret import interpret_captions
from .qc import apply_caption_approvals, is_approvable_issue, validate_document
from .overlays import (
    CaptionOverlay,
    CaptionApprovalLedger,
    CaptionOverlayApplication,
    CaptionOverlayOperation,
    CaptionOverlayOperationKind,
    InvalidCaptionOverlay,
    InvalidCaptionApprovals,
    apply_caption_overlay,
    caption_overlay_path,
    caption_approval_path,
    delete_caption_approvals,
    delete_caption_overlay,
    load_caption_overlay,
    load_caption_overlay_file,
    load_caption_approvals,
    load_caption_approvals_file,
    new_caption_approval,
    new_caption_overlay,
    save_caption_overlay,
    save_caption_approvals,
    revoke_caption_approval,
)

__all__ = [
    "CAPTION_ALGORITHM_VERSION",
    "CAPTION_SCHEMA_VERSION",
    "CONTRACT_EXAMPLES",
    "HOUSE_ENGLISH_V1",
    "CaptionBaselineCue",
    "CaptionApproval",
    "CaptionCharacterRange",
    "CaptionContentKind",
    "CaptionContext",
    "CaptionDestinationOverride",
    "CaptionDocument",
    "CaptionEditorialCoverage",
    "CaptionEvent",
    "CaptionExceptionState",
    "CaptionExportOptions",
    "CaptionExportPolicy",
    "CaptionFrameRate",
    "CaptionInterpretation",
    "CaptionIssueSeverity",
    "CaptionQCIssue",
    "CaptionQCReport",
    "CaptionProfile",
    "CaptionRenderingDisposition",
    "CaptionSource",
    "CaptionSourceToken",
    "CaptionTechnicalStatus",
    "CaptionTimingMode",
    "ExportResult",
    "InvalidNumericValue",
    "UnsupportedGlyph",
    "available_caption_profiles",
    "canonical_json",
    "deterministic_hash",
    "deterministic_id",
    "get_caption_profile",
    "is_supported_glyph",
    "repertoire_metadata",
    "unsupported_glyphs",
    "interpret_captions",
    "validate_document",
    "apply_caption_approvals",
    "is_approvable_issue",
    "CaptionOverlay",
    "CaptionApprovalLedger",
    "CaptionOverlayApplication",
    "CaptionOverlayOperation",
    "CaptionOverlayOperationKind",
    "InvalidCaptionOverlay",
    "InvalidCaptionApprovals",
    "apply_caption_overlay",
    "caption_overlay_path",
    "caption_approval_path",
    "delete_caption_approvals",
    "delete_caption_overlay",
    "load_caption_overlay",
    "load_caption_overlay_file",
    "load_caption_approvals",
    "load_caption_approvals_file",
    "new_caption_approval",
    "new_caption_overlay",
    "save_caption_overlay",
    "save_caption_approvals",
    "revoke_caption_approval",
]
